const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.MoveTo,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.HTMLElement,
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.HTMLElement.Acts.SetCSSStyle,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.HTMLElement.Cnds.CompareX,
		C3.Plugins.HTMLElement.Cnds.CompareInstanceVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.HTMLElement.Acts.SetContent,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.HTMLElement.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.HTMLElement.Acts.SetInstanceVar
	];
};
self.C3_JsPropNameTable = [
	{Arkaplan: 0},
	{SPR_donut: 0},
	{ŞurayaTaşı: 0},
	{SPR_man1: 0},
	{SPR_man2: 0},
	{SPR_gosterge1: 0},
	{SPR_gosterge2: 0},
	{baslandi: 0},
	{BTN_genel: 0},
	{Fare: 0},
	{Dokun: 0},
	{HTMLElementi_Soru: 0},
	{Dizi: 0},
	{deger: 0},
	{HTMLElementi_Secenekler: 0},
	{Sprite: 0},
	{Ses: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Yazı: 0},
	{Yazı2: 0},
	{tip: 0},
	{x: 0},
	{x_0: 0},
	{x_1: 0},
	{x_2: 0},
	{y: 0},
	{i: 0},
	{j: 0},
	{gecici: 0},
	{gosterge1: 0},
	{gosterge2: 0},
	{canli: 0},
	{sure: 0},
	{s: 0},
	{animekare: 0},
	{tahmin: 0},
	{islem: 0}
];

self.InstanceType = {
	Arkaplan: class extends self.ISpriteInstance {},
	SPR_donut: class extends self.ISpriteInstance {},
	SPR_man1: class extends self.ISpriteInstance {},
	SPR_man2: class extends self.ISpriteInstance {},
	SPR_gosterge1: class extends self.ISpriteInstance {},
	SPR_gosterge2: class extends self.ISpriteInstance {},
	BTN_genel: class extends self.ISpriteInstance {},
	Fare: class extends self.IInstance {},
	Dokun: class extends self.IInstance {},
	HTMLElementi_Soru: class extends self.IHTMLElementInstance {},
	Dizi: class extends self.IArrayInstance {},
	HTMLElementi_Secenekler: class extends self.IHTMLElementInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Ses: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Yazı: class extends self.ITextInstance {},
	Yazı2: class extends self.ITextInstance {}
}